@DotTime_HostAddress = http://localhost:5171

###
### Successful test: check response status is 200
GET {{DotTime_HostAddress}}/

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# @name Post Start Process
POST {{DotTime_HostAddress}}/process
X-Api-Version: 1.0.0
Content-Type: application/json
{
    "token": "xxxxx",
    "processes": [
        {
            "name": "test3",
            "history": [
                {
                    "timeStarted": "2022-01-01 00:00:00",
                    "timeEnded": ""
                }
            ] 
        }
    ]
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# @name Post End Process
POST {{DotTime_HostAddress}}/process
X-Api-Version: 1.0.0
Content-Type: application/json
{
  "token": "xxxxx",
  "processes": [
    {
      "name": "test3",
      "history": [
        {
          "timeStarted": "2022-01-01 00:00:00",
          "timeEnded": "2022-01-01 00:00:00"
        }
      ]
    }
  ]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
# @name Post Multiple Processes
POST {{DotTime_HostAddress}}/process
X-Api-Version: 1.0.0
Content-Type: application/json
{
  "token": "xxxxx",
  "version": "1.0.0",
  "processes": [
    {
      "name": "test3",
      "history": [
        {
          "timeStarted": "2022-01-01 00:00:00",
          "timeEnded": "2022-01-01 00:00:00"
        }
      ]
    }
    {
      "name": "test4",
      "history": [
        {
          "timeStarted": "2022-01-02 00:00:00",
          "timeEnded": "2022-01-03 00:00:00"
        },
        {
          "timeStarted": "2022-01-02 00:00:00",
          "timeEnded": "2022-01-03 00:00:00"
        },
        {
          "timeStarted": "2022-01-02 00:00:00",
          "time Ended": ""
        }
      ]
    }
  ]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}