name: Make&Push-API-Image
on: [push]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest podman
        if: matrix.install_latest
        run: |
          bash .github/install_latest_podman.sh
      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          image: DTAPI
          tags: latest ${{ github.sha }}
          containerfile: DTServerAPI/DockerFile
          oci: true
      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"